
---
Description:  Example Cloudformation Template
Parameters:  
  Subnet:
    Description: Where to put this instance
    Type:  AWS::EC2::Subnet::Id
  SecurityGroup:
    Type:  AWS::EC2::SecurityGroup::Id
  InstanceType:
    Type:  String
    Default:  t2.nano
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
Resources:
  MyInstance:
    Type:  AWS::EC2::Instance
    Properties:  
      ImageId:  ami-f173cc91
      InstanceType:  
        Ref: InstanceType
      SecurityGroupIds:  
        - Ref:  SecurityGroup
      SubnetId:
        Ref: Subnet
      UserData:
        Fn::Base64: | 
          #!/bin/bash -xe
          yum install nginx -y
          sudo service nginx start